# Build WAR
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'

# Copy WAR to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Confirm WAR is in staging
- script: ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'List staging directory contents'

# Deploy WAR from staging
- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/*.war'
    appType: webAppLinux
